In [1]:
%load_ext dotenv
%dotenv

# What are we doing?

## Objectives 


* Build a data pipeline that downloads price data from the internet, stores it locally, transforms it into return data, and stores the feature set.
    - Getting the data.
    - Schemas and index in dask.

* Explore the parquet format.
    - Reading and writing parquet files.
    - Read datasets that are stored in distributed files.
    - Discuss dask vs pandas as a small example of big vs small data.
    
* Discuss the use of environment variables for settings.
* Discuss how to use Jupyter notebooks and source code concurrently. 
* Logging and using a standard logger.

## About the Data

+ We will download the prices for a list of stocks.
+ The source is Yahoo Finance and we will use the API provided by the library yfinance.


## Medallion Architecture

+ The architecture that we are thinking about is called Medallion by [DataBricks](https://www.databricks.com/glossary/medallion-architecture). It is an ELT type of thinking, although our data is well-structured.

![Medallion Architecture (DataBicks)](./images/02_medallion_architecture.png)

+ In our case, we would like to optimize the number of times that we download data from the internet. 
+ Ultimately, we will build a pipeline manager class that will help us control the process of obtaining and transforming our data.

![](./images/02_target_pipeline_manager.png)

# Download Data from Yahoo Finance

Yahoo Finance provides information about public stocks in different markets. The library yfinance gives us access to a fair bit of the data in Yahoo Finance. 

These steps are based on the instructions in:

+ [yfinance documentation](https://pypi.org/project/yfinance/)
+ [Tutorial in geeksforgeeks.org](https://www.geeksforgeeks.org/get-financial-data-from-yahoo-finance-with-python/)

+ If required, install: `python -m pip install yfinance`.
+ To download the price history of a stock, first use the following setup:

In [2]:
import pandas as pd
import yfinance as yf
import os
import sys

sys.path.append(os.getenv('SRC_DIR'))

A few things to notice in the code chunk above:

+ Libraries are ordered from high-level to low-level libraries from the package manager (pip in this case, but could be conda, poetry, etc.)
+ The command `sys.path.append("../05_src/)` will add the `../05_src/` directory to the path in the Notebook's kernel. This way, we can use our modules as part of the notebook.
+ Local modules are imported at the end. 
+ The function `get_logger()` is called with `__name__` as recommended by the documentation.

Now, to download the historical price data for a stock, we could use:

In [3]:
px = yf.download('AAPL', start = "2013-12-01", end = "2024-02-01")
px

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,,
2013-12-02 00:00:00+00:00,17.175104,19.686787,20.154642,19.672144,19.928572,472544800
2013-12-03 00:00:00+00:00,17.645260,20.225714,20.227858,19.917143,19.939285,450968000
2013-12-04 00:00:00+00:00,17.604143,20.178572,20.328215,20.029285,20.196428,377809600
2013-12-05 00:00:00+00:00,17.694494,20.282143,20.540714,20.228930,20.451786,447580000
2013-12-06 00:00:00+00:00,17.448965,20.000713,20.241072,19.984644,20.206785,344352400
...,...,...,...,...,...,...
2024-01-25 00:00:00+00:00,193.223389,194.169998,196.270004,193.110001,195.220001,54822100
2024-01-26 00:00:00+00:00,191.481918,192.419998,194.759995,191.940002,194.270004,44594000
2024-01-29 00:00:00+00:00,190.795273,191.729996,192.199997,189.580002,192.009995,47145600
2024-01-30 00:00:00+00:00,187.123276,188.039993,191.800003,187.470001,190.940002,55859400
2024-01-31 00:00:00+00:00,183.501022,184.399994,187.100006,184.350006,187.039993,55467800

## Parametrize the download

+ Generally, we will look to separate every parameter and setting from functions.
+ If we had a few stocks, we could cycle through them. We need a place to store the list of tickers (a db or file, for example).
+ Store a csv file with a few stock tickers. The location of the file is a setting, the contents of this file are parameters.
+ Use **environment variables** to pass parameters.

Start by getting a sample of Information Technology stock tickers by applying subindexing and converting the "ticker" column from a pandas object to a list.

In [4]:
# Load all tickers
ticker_file = os.getenv("TICKERS")
tickers = pd.read_csv(ticker_file)
tickers

,ticker,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",20883,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",42942,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",20883,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",41274,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",40730,1467373,1989
...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",35709,1041061,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",43822,877212,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",37110,1136869,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",37064,109380,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",41446,1555280,1952

We can subset our ticker data set using standard indexing techniques. A good reference for this type of data manipulation is Panda's [Documentation](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-and-selecting-data) and [Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-selection).

In [5]:
idx_tech = tickers['GICS Sector'] == 'Information Technology'
tech_sector = tickers[idx_tech]
tech_sector

,ticker,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",40730,1467373,1989
5,ADBE,Adobe Inc.,Information Technology,Application Software,"San Jose, California",35555,796343,1982
6,AMD,Advanced Micro Devices,Information Technology,Semiconductors,"Santa Clara, California",42814,2488,1969
12,AKAM,Akamai,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",39275,1086222,1998
34,APH,Amphenol,Information Technology,Electronic Components,"Wallingford, Connecticut",39721,820313,1932
...,...,...,...,...,...,...,...,...
450,TRMB,Trimble Inc.,Information Technology,Electronic Equipment & Instruments,"Westminster, Colorado",44217,864749,1978
452,TYL,Tyler Technologies,Information Technology,Application Software,"Plano, Texas",44004,860731,1966
467,VRSN,Verisign,Information Technology,Internet Services & Infrastructure,"Dulles, Virginia",38749,1014473,1995
488,WDC,Western Digital,Information Technology,"Technology Hardware, Storage & Peripherals","San Jose, California",39995,106040,1970
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",43822,877212,1969

From the subset data frame, select one column and convert to list.

In [6]:
tech_tickers = tech_sector['ticker'].to_list()
tech_tickers

['ACN',
 'ADBE',
 'AMD',
 'AKAM',
 'APH',
 'ADI',
 'ANSS',
 'AAPL',
 'AMAT',
 'ANET',
 'ADSK',
 'AVGO',
 'CDNS',
 'CDW',
 'CSCO',
 'CTSH',
 'GLW',
 'ENPH',
 'EPAM',
 'FFIV',
 'FICO',
 'FSLR',
 'FTNT',
 'IT',
 'GEN',
 'HPE',
 'HPQ',
 'IBM',
 'INTC',
 'INTU',
 'JBL',
 'JNPR',
 'KEYS',
 'KLAC',
 'LRCX',
 'MCHP',
 'MU',
 'MSFT',
 'MPWR',
 'MSI',
 'NTAP',
 'NVDA',
 'NXPI',
 'ON',
 'ORCL',
 'PANW',
 'PTC',
 'QRVO',
 'QCOM',
 'ROP',
 'CRM',
 'STX',
 'NOW',
 'SWKS',
 'SNPS',
 'TEL',
 'TDY',
 'TER',
 'TXN',
 'TRMB',
 'TYL',
 'VRSN',
 'WDC',
 'ZBRA']

In [7]:
tech_raw_dt = yf.download(tech_tickers, start = "2000-01-01", end = "2025-01-26")
tech_raw_dt

[*********************100%***********************]  64 of 64 completed

Price                       Adj Close                                      \
Ticker                           AAPL         ACN        ADBE         ADI
Date
2000-01-03 00:00:00+00:00    0.843077         NaN   16.274672   28.095680
2000-01-04 00:00:00+00:00    0.771997         NaN   14.909401   26.674355
2000-01-05 00:00:00+00:00    0.783293         NaN   15.204176   27.063763
2000-01-06 00:00:00+00:00    0.715508         NaN   15.328288   26.323904
2000-01-07 00:00:00+00:00    0.749401         NaN   16.072985   27.063763
...                               ...         ...         ...         ...
2025-01-17 00:00:00+00:00  229.979996  352.589996  429.989990  219.160004
2025-01-21 00:00:00+00:00  222.639999  356.420013  436.359985  221.449997
2025-01-22 00:00:00+00:00  223.830002  359.109985  437.320007  224.080002
2025-01-23 00:00:00+00:00  223.660004  363.260010  437.279999  228.350006
2025-01-24 00:00:00+00:00  222.779999  362.410004  435.380005  217.369995

Price                                                                      \
Ticker                           ADSK        AKAM        AMAT         AMD
Date
2000-01-03 00:00:00+00:00    8.052906  321.250000   23.138014   15.500000
2000-01-04 00:00:00+00:00    7.660816  300.000000   21.994835   14.625000
2000-01-05 00:00:00+00:00    7.178246  283.500000   21.171740   15.000000
2000-01-06 00:00:00+00:00    6.740915  236.125000   21.206041   16.000000
2000-01-07 00:00:00+00:00    7.540174  248.375000   21.388945   16.250000
...                               ...         ...         ...         ...
2025-01-17 00:00:00+00:00  291.450012   91.010002  192.050003  121.459999
2025-01-21 00:00:00+00:00  296.910004   94.709999  192.869995  122.279999
2025-01-22 00:00:00+00:00  301.450012   95.110001  195.509995  123.750000
2025-01-23 00:00:00+00:00  301.079987   95.889999  190.699997  123.040001
2025-01-24 00:00:00+00:00  300.829987   97.699997  186.750000  122.839996

Price                                              ...   Volume          \
Ticker                           ANET        ANSS  ...     SWKS     TDY
Date                                               ...
2000-01-03 00:00:00+00:00         NaN    2.765625  ...   512000  315400
2000-01-04 00:00:00+00:00         NaN    2.687500  ...   292600  444300
2000-01-05 00:00:00+00:00         NaN    2.703125  ...   411800  109100
2000-01-06 00:00:00+00:00         NaN    2.703125  ...   385400  120700
2000-01-07 00:00:00+00:00         NaN    2.703125  ...   536000  222100
...                               ...         ...  ...      ...     ...
2025-01-17 00:00:00+00:00  119.949997  349.929993  ...  2150600  264400
2025-01-21 00:00:00+00:00  121.500000  352.070007  ...  2389300  377400
2025-01-22 00:00:00+00:00  129.820007  356.630005  ...  2774100  668700
2025-01-23 00:00:00+00:00  129.119995  360.359985  ...  1777300  384700
2025-01-24 00:00:00+00:00  129.169998  357.369995  ...  1803300  333500

Price                                                                     \
Ticker                           TEL      TER     TRMB       TXN     TYL
Date
2000-01-03 00:00:00+00:00        NaN  1353500  8025000  10815600  138300
2000-01-04 00:00:00+00:00        NaN  1611800  4963200   7952400  135100
2000-01-05 00:00:00+00:00        NaN  1855800  1930200  12142400  187200
2000-01-06 00:00:00+00:00        NaN   964700  2230800  11758400  107200
2000-01-07 00:00:00+00:00        NaN   809200  2166600  12938800   78900
...                              ...      ...      ...       ...     ...
2025-01-17 00:00:00+00:00  4102600.0  2253700  1010700   5407500  308000
2025-01-21 00:00:00+00:00  2568300.0  4083000  1341800   9621700  235400
2025-01-22 00:00:00+00:00  3162200.0  2262100  1098600   8222000  177300
2025-01-23 00:00:00+00:00  1417800.0  2214300  1210400  12694700  214000
2025-01-24 00:00:00+00:00  1017300.0  2254000   895300  15856600  155300

Price
Ticker                        VRSN      WDC     ZBRA
Date
2000-01-03 00:00:00+00:00  2270100  2461900  1055700
2000-01-04 00:00:00+00:00  3002200  7660300   522450
2000-01-05 00:00:00+00:00  6886600  3944600   612225
2000-01-06 00:00:00+00:00  4003200  2468400   263925
2000-01-07 00:00:00+00:00  3803200  9783000   333900
...                            ...      ...      ...
2025-01-17 00:00:00+00:00   503300  7160500   270600
2025-01-21 00:00:00+00:00   781800  7045600   446000
2025-01-22 00:00:00+00:00   674500  9340500   497500
2025-01-23 00:00:00+00:00   630100  7059500   377100
2025-01-24 00:00:00+00:00   563300  6046500   258900

[6304 rows x 384 columns]

The data that we downloaded combines several stocks and prices into a single row. We want to parse this arrangement into a dataframe that contains observations about a single stock on a given day per row. To do this, we can use the function [`stack()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html) and re-arrange the indices.

In [8]:
# First, check what tech_raw_dt.stack() looks like.
tech_raw_dt.stack(future_stack=True).reset_index()

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume
0,2000-01-03 00:00:00+00:00,AAPL,0.843077,0.999442,1.004464,0.907924,0.936384,535796800.0
1,2000-01-03 00:00:00+00:00,ACN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-01-03 00:00:00+00:00,ADBE,16.274672,16.390625,16.875000,16.062500,16.812500,7384400.0
3,2000-01-03 00:00:00+00:00,ADI,28.095680,45.093750,46.937500,44.000000,46.750000,3655600.0
4,2000-01-03 00:00:00+00:00,ADSK,8.052906,8.343750,8.656250,8.031250,8.500000,2845600.0
...,...,...,...,...,...,...,...,...
403451,2025-01-24 00:00:00+00:00,TXN,185.520004,185.520004,191.500000,185.029999,190.000000,15856600.0
403452,2025-01-24 00:00:00+00:00,TYL,591.929993,591.929993,594.969971,590.210022,591.400024,155300.0
403453,2025-01-24 00:00:00+00:00,VRSN,210.729996,210.729996,210.880005,206.009995,206.020004,563300.0
403454,2025-01-24 00:00:00+00:00,WDC,67.410004,67.410004,69.440002,67.360001,68.910004,6046500.0
403455,2025-01-24 00:00:00+00:00,ZBRA,414.609985,414.609985,420.079987,413.739990,419.059998,258900.0

In [9]:
tech_dt = (tech_raw_dt
           .stack(future_stack=True)
           .reset_index()
           .sort_values(['Ticker', 'Date']))
tech_dt.columns.name = None

# Storing Data in CSV

+ We have some data. How do we store it?
+ We can compare two options, CSV and Parqruet, by measuring their performance:

    - Time to save.
    - Space required.

In [10]:
def get_dir_size(path='.'):
    '''Returns the total size of files contained in path.'''
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_dir_size(entry.path)
    return total

In [11]:
import time

In [12]:
temp = os.getenv("TEMP_DATA")
os.makedirs(temp, exist_ok=True)
stock_path = os.path.join(temp, "stock_px.csv")

In [13]:
start = time.time()
tech_dt.to_csv(stock_path, index = False)
end = time.time()

print(f'Writing to dt ({tech_dt.shape})csv took {end - start} seconds.')
print(f'Csv file size { os.path.getsize(stock_path)*1e-6 } MB')

Writing to dt ((403456, 8))csv took 4.803917169570923 seconds.
Csv file size 47.817460999999994 MB

## Save Data to Parquet

### Dask 

We can work with with large data sets and parquet files. In fact, recent versions of pandas support pyarrow data types and future versions will require a pyarrow backend. The pyarrow library is an interface between Python and the Appache Arrow project. The [parquet data format](https://parquet.apache.org/) and [Arrow](https://arrow.apache.org/docs/python/parquet.html) are projects of the Apache Foundation.

However, Dask is much more than an interface to Arrow: Dask provides parallel and distributed computing on pandas-like dataframes. It is also relatively easy to use, bridging a gap between pandas and Spark.

In [14]:
import dask.dataframe as dd

c:\Users\syeolekar\.conda\envs\dsi_participant\lib\site-packages\dask\dataframe\_pyarrow_compat.py:15: FutureWarning: Minimal version of pyarrow will soon be increased to 14.0.1. You are using 11.0.0. Please consider upgrading.
  warnings.warn(

In [15]:
px_dd = dd.from_pandas(tech_dt, npartitions = len(tech_tickers))
parquet_path = os.path.join(temp, "stock_px.parquet")

start = time.time()
px_dd.to_parquet(parquet_path, engine = "pyarrow")
end = time.time()

print(f'Writing dd ({tech_dt.shape}) to parquet took {end - start} seconds.')
print(f'Parquet file size { get_dir_size(parquet_path)*1e-6 } MB')

Writing dd ((403456, 8)) to parquet took 0.7775530815124512 seconds.
Parquet file size 16.59562 MB

### Parquet files and Dask Dataframes

+ Parquet files are immutable: once written, they cannot be modified.
+ Dask DataFrames are a useful implementation to manipulate data stored in parquets.
+ Parquet and Dask are not the same: parquet is a file format that can be accessed by many applications and programming languages (Python, R, PowerBI, etc.), while Dask is a package in Python to work with large datasets using distributed computation.
+ **Dask is not for everything** (see [Dask DataFrames Best Practices](https://docs.dask.org/en/stable/dataframe-best-practices.html)). 

    - Consider cases suchas small to large joins, where the small dataframe fits in memory, but the large one does not. 
    - If possible, use pandas: reduce, then use pandas.
    - Pandas performance tips apply to Dask.
    - Use the index: it is beneficial to have a well-defined index in Dask DataFrames, as it may speed up searching (filtering) the data. A one-dimensional index is allowed.
    - Avoid (or minimize) full-data shuffling: indexing is an expensive operations. 
    - Some joins are more expensive than others. 

        * Not expensive:

            - Join a Dask DataFrame with a pandas DataFrame.
            - Join a Dask DataFrame with another Dask DataFrame of a single partition.
            - Join Dask DataFrames along their indexes.

        * Expensive:

            - Join Dask DataFrames along columns that are not their index.

# How do we store prices?

+ We can store our data as a single blob. This can be difficult to maintain, especially because parquet files are immutable.
+ Strategy: organize data files by ticker and date. Update only latest month.

In [16]:
# CLean up before start
PRICE_DATA = os.getenv("PRICE_DATA")
import shutil
if os.path.exists(PRICE_DATA):
    shutil.rmtree(PRICE_DATA)

In [17]:
for ticker in tech_dt['Ticker'].unique():
    ticker_dt = tech_dt[tech_dt['Ticker'] == ticker]
    ticker_dt = ticker_dt.assign(Year = ticker_dt.Date.dt.year)
    for yr in ticker_dt['Year'].unique():
        yr_dd = dd.from_pandas(ticker_dt[ticker_dt['Year'] == yr],2)
        yr_path = os.path.join(PRICE_DATA, ticker, f"{ticker}_{yr}")
        os.makedirs(os.path.dirname(yr_path), exist_ok=True)
        yr_dd.to_parquet(yr_path, engine = "pyarrow")

Why would we want to store data this way?

+ Easier to maintain. We do not update old data, only recent data.
+ We can also access all files as follows.

# Load, Transform and Save

## Load

+ Parquet files can be read individually or as a collection.
+ `dd.read_parquet()` can take a list (collection) of files as input.
+ Use `glob` to get the collection of files.

In [18]:
from glob import glob

parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True)
dd_px = dd.read_parquet(parquet_files).set_index("Ticker")
dd_px

Dask DataFrame Structure:
                               Date Adj Close    Close     High      Low     Open   Volume   Year
npartitions=64
AAPL            datetime64[ns, UTC]   float64  float64  float64  float64  float64  float64  int32
ACN                             ...       ...      ...      ...      ...      ...      ...    ...
...                             ...       ...      ...      ...      ...      ...      ...    ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...
Dask Name: setindex, 2 expressions
Expr=SetIndex(frame=ReadParquetFSSpec(f633528), _other='Ticker', options={})

## Transform

+ This transformation step will create a *Features* data set. In our case, features will be stock returns (we obtained prices).
+ Dask dataframes work like pandas dataframes: in particular, we can perform groupby and apply operations.
+ Notice the use of [an anonymous (lambda) function](https://realpython.com/python-lambda/) in the apply statement.

In [19]:
dd_shift = dd_px.groupby('Ticker', group_keys=False).apply(
    lambda x: x.assign(Close_lag_1 = x['Close'].shift(1))
)

C:\Users\syeolekar\AppData\Local\Temp\ipykernel_808\3086392435.py:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  dd_shift = dd_px.groupby('Ticker', group_keys=False).apply(

In [20]:
dd_rets = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)

## Lazy Exection

What does `dd_rets` contain?

In [21]:
dd_rets

Dask DataFrame Structure:
                               Date Adj Close    Close     High      Low     Open   Volume   Year Close_lag_1  Returns
npartitions=64
AAPL            datetime64[ns, UTC]   float64  float64  float64  float64  float64  float64  int32     float64  float64
ACN                             ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
...                             ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
Dask Name: assign, 9 expressions
Expr=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(f633528), _other='Ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x000001D636715790>, meta=<no_default>, args=(), kwargs={})))

+ Dask is a lazy execution framework: commands will not execute until they are required. 
+ To trigger an execution in dask use `.compute()`.

In [22]:
dd_rets.compute()

,Date,Adj Close,Close,High,Low,Open,Volume,Year,Close_lag_1,Returns
Ticker,,,,,,,,,,
AAPL,2000-01-03 00:00:00+00:00,0.843077,0.999442,1.004464,0.907924,0.936384,535796800.0,2000,NaN,NaN
AAPL,2000-01-04 00:00:00+00:00,0.771997,0.915179,0.987723,0.903460,0.966518,512377600.0,2000,0.999442,-0.084310
AAPL,2000-01-05 00:00:00+00:00,0.783293,0.928571,0.987165,0.919643,0.926339,778321600.0,2000,0.915179,0.014633
AAPL,2000-01-06 00:00:00+00:00,0.715508,0.848214,0.955357,0.848214,0.947545,767972800.0,2000,0.928571,-0.086538
AAPL,2000-01-07 00:00:00+00:00,0.749401,0.888393,0.901786,0.852679,0.861607,460734400.0,2000,0.848214,0.047369
...,...,...,...,...,...,...,...,...,...,...
ZBRA,2025-01-17 00:00:00+00:00,405.709991,405.709991,407.290009,402.290009,406.040009,270600.0,2025,402.720001,0.007424
ZBRA,2025-01-21 00:00:00+00:00,418.070007,418.070007,419.850006,407.619995,407.619995,446000.0,2025,405.709991,0.030465
ZBRA,2025-01-22 00:00:00+00:00,420.570007,420.570007,427.760010,419.589996,425.239990,497500.0,2025,418.070007,0.005980
ZBRA,2025-01-23 00:00:00+00:00,421.109985,421.109985,422.290009,414.450012,417.619995,377100.0,2025,420.570007,0.001284
ZBRA,2025-01-24 00:00:00+00:00,414.609985,414.609985,420.079987,413.739990,419.059998,258900.0,2025,421.109985,-0.015435

## Save

+ Apply transformations to calculate daily returns
+ Store the enriched data, the silver dataset, in a new directory.
+ Should we keep the same namespace? All columns?

In [23]:
# CLean up before save
FEATURES_DATA = os.getenv("FEATURES_DATA")
if os.path.exists(FEATURES_DATA):
    shutil.rmtree(FEATURES_DATA)
dd_rets.to_parquet(FEATURES_DATA, overwrite = True)
dd_rets

Dask DataFrame Structure:
                               Date Adj Close    Close     High      Low     Open   Volume   Year Close_lag_1  Returns
npartitions=64
AAPL            datetime64[ns, UTC]   float64  float64  float64  float64  float64  float64  int32     float64  float64
ACN                             ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
...                             ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
ZBRA                            ...       ...      ...      ...      ...      ...      ...    ...         ...      ...
Dask Name: assign, 9 expressions
Expr=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(f633528), _other='Ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x000001D636715790>, meta=<no_default>, args=(), kwargs={})))

# Optional: from Jupyter to Command Line

+ We have drafted our code in a Jupyter Notebook. 
+ Finalized code should be written in Python modules.

## Object Oriented vs Functional Programming

+ We can use classes to keep parameters and functions together.
+ We *could* use Object Oriented Programming, but parallelization of data manipulation and modelling tasks benefit from *Functional Programming*.
+ An Idea: 

    - [Data Oriented Programming](https://blog.klipse.tech/dop/2022/06/22/principles-of-dop.html).
    - Use the class to bundle together parameters and functions.
    - Use stateless operations and treat all data objects as immutable (we do not modify them, we overwrite them).
    - Take advantage of [`@staticmethod`](https://realpython.com/instance-class-and-static-methods-demystified/).

The code is in `./05_src/`.

Our original design was:

![](./images/02_target_pipeline_manager.png)

The `DataManager` class in `./05_src/data_manager.py` is a simple implementation of the ideas and code discussed in this notebook. The lines below will download data for about 500 stocks from the S&P500. Using this data a few features will be created and stored in the features data set.

First, instantiate an object of class `DataManager`.

In [24]:
from data_manager import DataManager
dm = DataManager()

Download all prices.

In [25]:
dm.download_all()

2025-01-31 17:49:29,298, data_manager.py, 42, INFO, Getting price data for all tickers.
2025-01-31 17:49:29,300, data_manager.py, 51, INFO, Getting tickers from ../../05_src/data/tickers/sp500_wiki.csv
2025-01-31 17:49:29,308, data_manager.py, 57, INFO, Processing all tickers
2025-01-31 17:49:29,310, data_manager.py, 70, INFO, Processing ticker ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BK', 'BBWI', 'BAX', 'BDX', 'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BX', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BLDR', 'BG', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'COR', 'CNC', 'CNP', 'CF', 'CHRW', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DVA', 'DAY', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'EG', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GEHC', 'GEN', 'GNRC', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WRB', 'WAB', 'WBA', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS']
2025-01-31 17:49:29,312, data_manager.py, 100, INFO, Getting stock price data for ['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BK', 'BBWI', 'BAX', 'BDX', 'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BX', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BLDR', 'BG', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'COR', 'CNC', 'CNP', 'CF', 'CHRW', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DVA', 'DAY', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'EG', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GEHC', 'GEN', 'GNRC', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WRB', 'WAB', 'WBA', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS'] from 2000-01-01 to 2025-01-31
[*********************100%***********************]  503 of 503 completed

7 Failed downloads:
['PEAK', 'BRK.B', 'FLT', 'PXD', 'WRK', 'MRO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2000-01-01 -> 2025-01-31)')
2025-01-31 17:50:20,414, data_manager.py, 80, INFO, Saving data by year
2025-01-31 17:50:20,764, data_manager.py, 83, INFO, Saving data for A
2025-01-31 17:50:21,379, data_manager.py, 83, INFO, Saving data for AAL
2025-01-31 17:50:22,044, data_manager.py, 83, INFO, Saving data for AAPL
2025-01-31 17:50:22,720, data_manager.py, 83, INFO, Saving data for ABBV
2025-01-31 17:50:23,353, data_manager.py, 83, INFO, Saving data for ABNB
2025-01-31 17:50:23,990, data_manager.py, 83, INFO, Saving data for ABT
2025-01-31 17:50:24,694, data_manager.py, 83, INFO, Saving data for ACGL
2025-01-31 17:50:25,373, data_manager.py, 83, INFO, Saving data for ACN
2025-01-31 17:50:26,160, data_manager.py, 83, INFO, Saving data for ADBE
2025-01-31 17:50:27,117, data_manager.py, 83, INFO, Saving data for ADI
2025-01-31 17:50:28,039, data_manager.py, 83, INFO, Saving data for ADM
2025-01-31 17:50:29,114, data_manager.py, 83, INFO, Saving data for ADP
2025-01-31 17:50:29,982, data_manager.py, 83, INFO, Saving data for ADSK
2025-01-31 17:50:30,963, data_manager.py, 83, INFO, Saving data for AEE
2025-01-31 17:50:31,827, data_manager.py, 83, INFO, Saving data for AEP
2025-01-31 17:50:32,534, data_manager.py, 83, INFO, Saving data for AES
2025-01-31 17:50:33,234, data_manager.py, 83, INFO, Saving data for AFL
2025-01-31 17:50:33,920, data_manager.py, 83, INFO, Saving data for AIG
2025-01-31 17:50:34,666, data_manager.py, 83, INFO, Saving data for AIZ
2025-01-31 17:50:35,372, data_manager.py, 83, INFO, Saving data for AJG
2025-01-31 17:50:36,044, data_manager.py, 83, INFO, Saving data for AKAM
2025-01-31 17:50:36,753, data_manager.py, 83, INFO, Saving data for ALB
2025-01-31 17:50:37,436, data_manager.py, 83, INFO, Saving data for ALGN
2025-01-31 17:50:38,114, data_manager.py, 83, INFO, Saving data for ALL
2025-01-31 17:50:38,807, data_manager.py, 83, INFO, Saving data for ALLE
2025-01-31 17:50:39,490, data_manager.py, 83, INFO, Saving data for AMAT
2025-01-31 17:50:40,195, data_manager.py, 83, INFO, Saving data for AMCR
2025-01-31 17:50:40,859, data_manager.py, 83, INFO, Saving data for AMD
2025-01-31 17:50:41,624, data_manager.py, 83, INFO, Saving data for AME
2025-01-31 17:50:42,294, data_manager.py, 83, INFO, Saving data for AMGN
2025-01-31 17:50:43,150, data_manager.py, 83, INFO, Saving data for AMP
2025-01-31 17:50:43,899, data_manager.py, 83, INFO, Saving data for AMT
2025-01-31 17:50:44,573, data_manager.py, 83, INFO, Saving data for AMZN
2025-01-31 17:50:45,247, data_manager.py, 83, INFO, Saving data for ANET
2025-01-31 17:50:45,946, data_manager.py, 83, INFO, Saving data for ANSS
2025-01-31 17:50:46,753, data_manager.py, 83, INFO, Saving data for AON
2025-01-31 17:50:47,559, data_manager.py, 83, INFO, Saving data for AOS
2025-01-31 17:50:48,349, data_manager.py, 83, INFO, Saving data for APA
2025-01-31 17:50:49,312, data_manager.py, 83, INFO, Saving data for APD
2025-01-31 17:50:50,173, data_manager.py, 83, INFO, Saving data for APH
2025-01-31 17:50:51,032, data_manager.py, 83, INFO, Saving data for APTV
2025-01-31 17:50:51,828, data_manager.py, 83, INFO, Saving data for ARE
2025-01-31 17:50:52,818, data_manager.py, 83, INFO, Saving data for ATO
2025-01-31 17:50:53,725, data_manager.py, 83, INFO, Saving data for AVB
2025-01-31 17:50:54,539, data_manager.py, 83, INFO, Saving data for AVGO
2025-01-31 17:50:55,533, data_manager.py, 83, INFO, Saving data for AVY
2025-01-31 17:50:56,251, data_manager.py, 83, INFO, Saving data for AWK
2025-01-31 17:50:56,936, data_manager.py, 83, INFO, Saving data for AXON
2025-01-31 17:50:57,809, data_manager.py, 83, INFO, Saving data for AXP
2025-01-31 17:50:58,598, data_manager.py, 83, INFO, Saving data for AZO
2025-01-31 17:50:59,365, data_manager.py, 83, INFO, Saving data for BA
2025-01-31 17:51:00,077, data_manager.py, 83, INFO, Saving data for BAC
2025-01-31 17:51:00,868, data_manager.py, 83, INFO, Saving data for BALL
2025-01-31 17:51:01,565, data_manager.py, 83, INFO, Saving data for BAX
2025-01-31 17:51:02,372, data_manager.py, 83, INFO, Saving data for BBWI
2025-01-31 17:51:03,203, data_manager.py, 83, INFO, Saving data for BBY
2025-01-31 17:51:04,067, data_manager.py, 83, INFO, Saving data for BDX
2025-01-31 17:51:04,924, data_manager.py, 83, INFO, Saving data for BEN
2025-01-31 17:51:05,718, data_manager.py, 83, INFO, Saving data for BF.B
2025-01-31 17:51:06,444, data_manager.py, 83, INFO, Saving data for BG
2025-01-31 17:51:07,300, data_manager.py, 83, INFO, Saving data for BIIB
2025-01-31 17:51:08,353, data_manager.py, 83, INFO, Saving data for BIO
2025-01-31 17:51:09,238, data_manager.py, 83, INFO, Saving data for BK
2025-01-31 17:51:10,021, data_manager.py, 83, INFO, Saving data for BKNG
2025-01-31 17:51:10,970, data_manager.py, 83, INFO, Saving data for BKR
2025-01-31 17:51:11,827, data_manager.py, 83, INFO, Saving data for BLDR
2025-01-31 17:51:12,842, data_manager.py, 83, INFO, Saving data for BLK
2025-01-31 17:51:13,539, data_manager.py, 83, INFO, Saving data for BMY
2025-01-31 17:51:14,269, data_manager.py, 83, INFO, Saving data for BR
2025-01-31 17:51:14,971, data_manager.py, 83, INFO, Saving data for BRK.B
2025-01-31 17:51:15,653, data_manager.py, 83, INFO, Saving data for BRO
2025-01-31 17:51:16,359, data_manager.py, 83, INFO, Saving data for BSX
2025-01-31 17:51:17,304, data_manager.py, 83, INFO, Saving data for BWA
2025-01-31 17:51:18,135, data_manager.py, 83, INFO, Saving data for BX
2025-01-31 17:51:19,129, data_manager.py, 83, INFO, Saving data for BXP
2025-01-31 17:51:20,001, data_manager.py, 83, INFO, Saving data for C
2025-01-31 17:51:20,758, data_manager.py, 83, INFO, Saving data for CAG
2025-01-31 17:51:21,535, data_manager.py, 83, INFO, Saving data for CAH
2025-01-31 17:51:22,293, data_manager.py, 83, INFO, Saving data for CARR
2025-01-31 17:51:23,036, data_manager.py, 83, INFO, Saving data for CAT
2025-01-31 17:51:23,835, data_manager.py, 83, INFO, Saving data for CB
2025-01-31 17:51:24,808, data_manager.py, 83, INFO, Saving data for CBOE
2025-01-31 17:51:25,619, data_manager.py, 83, INFO, Saving data for CBRE
2025-01-31 17:51:26,386, data_manager.py, 83, INFO, Saving data for CCI
2025-01-31 17:51:27,179, data_manager.py, 83, INFO, Saving data for CCL
2025-01-31 17:51:28,057, data_manager.py, 83, INFO, Saving data for CDNS
2025-01-31 17:51:28,854, data_manager.py, 83, INFO, Saving data for CDW
2025-01-31 17:51:29,646, data_manager.py, 83, INFO, Saving data for CE
2025-01-31 17:51:30,420, data_manager.py, 83, INFO, Saving data for CEG
2025-01-31 17:51:31,172, data_manager.py, 83, INFO, Saving data for CF
2025-01-31 17:51:31,949, data_manager.py, 83, INFO, Saving data for CFG
2025-01-31 17:51:32,756, data_manager.py, 83, INFO, Saving data for CHD
2025-01-31 17:51:33,528, data_manager.py, 83, INFO, Saving data for CHRW
2025-01-31 17:51:34,325, data_manager.py, 83, INFO, Saving data for CHTR
2025-01-31 17:51:35,100, data_manager.py, 83, INFO, Saving data for CI
2025-01-31 17:51:35,865, data_manager.py, 83, INFO, Saving data for CINF
2025-01-31 17:51:36,681, data_manager.py, 83, INFO, Saving data for CL
2025-01-31 17:51:37,468, data_manager.py, 83, INFO, Saving data for CLX
2025-01-31 17:51:38,333, data_manager.py, 83, INFO, Saving data for CMA
2025-01-31 17:51:39,129, data_manager.py, 83, INFO, Saving data for CMCSA
2025-01-31 17:51:39,898, data_manager.py, 83, INFO, Saving data for CME
2025-01-31 17:51:40,740, data_manager.py, 83, INFO, Saving data for CMG
2025-01-31 17:51:41,519, data_manager.py, 83, INFO, Saving data for CMI
2025-01-31 17:51:42,302, data_manager.py, 83, INFO, Saving data for CMS
2025-01-31 17:51:43,119, data_manager.py, 83, INFO, Saving data for CNC
2025-01-31 17:51:43,897, data_manager.py, 83, INFO, Saving data for CNP
2025-01-31 17:51:44,655, data_manager.py, 83, INFO, Saving data for COF
2025-01-31 17:51:45,420, data_manager.py, 83, INFO, Saving data for COO
2025-01-31 17:51:46,158, data_manager.py, 83, INFO, Saving data for COP
2025-01-31 17:51:46,891, data_manager.py, 83, INFO, Saving data for COR
2025-01-31 17:51:47,649, data_manager.py, 83, INFO, Saving data for COST
2025-01-31 17:51:48,396, data_manager.py, 83, INFO, Saving data for CPB
2025-01-31 17:51:49,252, data_manager.py, 83, INFO, Saving data for CPRT
2025-01-31 17:51:50,362, data_manager.py, 83, INFO, Saving data for CPT
2025-01-31 17:51:51,264, data_manager.py, 83, INFO, Saving data for CRL
2025-01-31 17:51:52,116, data_manager.py, 83, INFO, Saving data for CRM
2025-01-31 17:51:52,920, data_manager.py, 83, INFO, Saving data for CSCO
2025-01-31 17:51:53,656, data_manager.py, 83, INFO, Saving data for CSGP
2025-01-31 17:51:54,429, data_manager.py, 83, INFO, Saving data for CSX
2025-01-31 17:51:55,166, data_manager.py, 83, INFO, Saving data for CTAS
2025-01-31 17:51:55,871, data_manager.py, 83, INFO, Saving data for CTLT
2025-01-31 17:51:56,625, data_manager.py, 83, INFO, Saving data for CTRA
2025-01-31 17:51:57,361, data_manager.py, 83, INFO, Saving data for CTSH
2025-01-31 17:51:58,164, data_manager.py, 83, INFO, Saving data for CTVA
2025-01-31 17:51:58,991, data_manager.py, 83, INFO, Saving data for CVS
2025-01-31 17:51:59,712, data_manager.py, 83, INFO, Saving data for CVX
2025-01-31 17:52:00,435, data_manager.py, 83, INFO, Saving data for CZR
2025-01-31 17:52:01,194, data_manager.py, 83, INFO, Saving data for D
2025-01-31 17:52:01,972, data_manager.py, 83, INFO, Saving data for DAL
2025-01-31 17:52:02,691, data_manager.py, 83, INFO, Saving data for DAY
2025-01-31 17:52:03,404, data_manager.py, 83, INFO, Saving data for DD
2025-01-31 17:52:04,117, data_manager.py, 83, INFO, Saving data for DE
2025-01-31 17:52:04,851, data_manager.py, 83, INFO, Saving data for DFS
2025-01-31 17:52:05,602, data_manager.py, 83, INFO, Saving data for DG
2025-01-31 17:52:06,309, data_manager.py, 83, INFO, Saving data for DGX
2025-01-31 17:52:07,037, data_manager.py, 83, INFO, Saving data for DHI
2025-01-31 17:52:07,825, data_manager.py, 83, INFO, Saving data for DHR
2025-01-31 17:52:08,562, data_manager.py, 83, INFO, Saving data for DIS
2025-01-31 17:52:09,281, data_manager.py, 83, INFO, Saving data for DLR
2025-01-31 17:52:10,384, data_manager.py, 83, INFO, Saving data for DLTR
2025-01-31 17:52:11,339, data_manager.py, 83, INFO, Saving data for DOV
2025-01-31 17:52:12,066, data_manager.py, 83, INFO, Saving data for DOW
2025-01-31 17:52:12,764, data_manager.py, 83, INFO, Saving data for DPZ
2025-01-31 17:52:13,498, data_manager.py, 83, INFO, Saving data for DRI
2025-01-31 17:52:14,232, data_manager.py, 83, INFO, Saving data for DTE
2025-01-31 17:52:14,966, data_manager.py, 83, INFO, Saving data for DUK
2025-01-31 17:52:15,677, data_manager.py, 83, INFO, Saving data for DVA
2025-01-31 17:52:16,436, data_manager.py, 83, INFO, Saving data for DVN
2025-01-31 17:52:17,179, data_manager.py, 83, INFO, Saving data for DXCM
2025-01-31 17:52:17,961, data_manager.py, 83, INFO, Saving data for EA
2025-01-31 17:52:18,710, data_manager.py, 83, INFO, Saving data for EBAY
2025-01-31 17:52:19,420, data_manager.py, 83, INFO, Saving data for ECL
2025-01-31 17:52:20,158, data_manager.py, 83, INFO, Saving data for ED
2025-01-31 17:52:20,888, data_manager.py, 83, INFO, Saving data for EFX
2025-01-31 17:52:21,627, data_manager.py, 83, INFO, Saving data for EG
2025-01-31 17:52:22,351, data_manager.py, 83, INFO, Saving data for EIX
2025-01-31 17:52:23,069, data_manager.py, 83, INFO, Saving data for EL
2025-01-31 17:52:23,760, data_manager.py, 83, INFO, Saving data for ELV
2025-01-31 17:52:24,493, data_manager.py, 83, INFO, Saving data for EMN
2025-01-31 17:52:25,219, data_manager.py, 83, INFO, Saving data for EMR
2025-01-31 17:52:25,954, data_manager.py, 83, INFO, Saving data for ENPH
2025-01-31 17:52:26,695, data_manager.py, 83, INFO, Saving data for EOG
2025-01-31 17:52:27,424, data_manager.py, 83, INFO, Saving data for EPAM
2025-01-31 17:52:28,201, data_manager.py, 83, INFO, Saving data for EQIX
2025-01-31 17:52:28,955, data_manager.py, 83, INFO, Saving data for EQR

Finally, add features to the data set and save to a *feature store*.

In [26]:
dm.featurize()

2025-01-31 17:57:06,928, data_manager.py, 114, INFO, Creating features data.
2025-01-31 17:57:06,931, data_manager.py, 124, INFO, Loading price data from ../../05_src/data/prices/
2025-01-31 17:57:15,060, data_manager.py, 133, INFO, Creating features
c:\Users\syeolekar\production\production\01_materials\labs\../../05_src\data_manager.py:136: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  features = (price_dd.groupby('Ticker', group_keys=False)
2025-01-31 17:57:15,068, data_manager.py, 158, INFO, Saving features to ../../05_src/data/features/stock_features.parquet